require authentication for / (frontend)
(https://github.com/lambdatrade/lambdatrade/issues/455)

diff --git a/tests/test b/tests/test
--- a/tests/test
+++ b/tests/test
@@ -351,13 +351,26 @@ docker_test() {
       exit 1
     fi
 
-    echo "Trying index.html without token (should fail)"
+    echo "Trying / without token (should fail)"
+    RES=$($CURL http://$DOCKER_HOST/ )
+    if [[ $RES != "Authenticate!" ]]; then
+      echo "Did not receive Authenticate!, gor $RES instead"
+      exit 1
+    fi
+
+    echo "Trying /index.html without token (should fail)"
     RES=$($CURL http://$DOCKER_HOST/index.html )
     if [[ $RES != "Authenticate!" ]]; then
       echo "Did not receive Authenticate!, gor $RES instead"
       exit 1
     fi
 
+    echo "Trying /foo.html without token"
+    RES=$($CURL http://$DOCKER_HOST/foo.html )
+    if [[ $RES != "foo!" ]]; then
+      echo "Did not receive Authenticate!, gor $RES instead"
+      exit 1
+    fi
 
     echo "Testing otp"
     create_otp $USER2 $PASSWORD2
