Allow /index.html be accessed without instance set
(https://github.com/lambdatrade/lambdatrade/issues/455)

diff --git a/tests/test b/tests/test
--- a/tests/test
+++ b/tests/test
@@ -270,19 +270,6 @@ docker_test() {
       exit 1
     fi
 
-    echo "Trying If-Modified-Since"
-    RES=$($CURL --cookie "token=$TOKEN" \
-                -H "X-Instance: $INSTANCE" \
-                -H "If-Modified-Since: $LASTMOD" \
-                -o /dev/null \
-                -w %{http_code} \
-                http://$DOCKER_HOST/index.html
-       )
-    if [[ $RES != "304" ]]; then
-      echo "If-Modified-Since did not result in 304, got $RES instead"
-      exit 1
-    fi
-
     echo "Trying If-None-Match"
     RES=$($CURL --cookie "token=$TOKEN" \
                 -H "X-Instance: $INSTANCE" \
@@ -352,6 +339,25 @@ docker_test() {
       echo "If-Modified-Since + If-None-Match did not result in 304, got $RES instead"
       exit 1
     fi
+
+    echo "Trying index.html without instance"
+    RES=$($CURL --cookie "token=$TOKEN" \
+                -o /dev/null \
+                -w %{http_code} \
+                http://$DOCKER_HOST/index.html
+       )
+    if [[ $RES != "200" ]]; then
+      echo "Could not get index.html without instance"
+      exit 1
+    fi
+
+    echo "Trying index.html without token (should fail)"
+    RES=$($CURL http://$DOCKER_HOST/index.html )
+    if [[ $RES != "Authenticate!" ]]; then
+      echo "Did not receive Authenticate!, gor $RES instead"
+      exit 1
+    fi
+
 
     echo "Testing otp"
     create_otp $USER2 $PASSWORD2
