Add endpoint to change passwords
Example usage

```
curl -XPOST \
     -H 'X-Instance: de305d54-75b4-431b-adb2-eb6b9e546014' \
     -H 'X-Token: SYE84jet45kaYeL5JXdfvn' \
     -H 'Content-Type: application/json' \
     -d '{"oldPasword":"pwd123","newPassword":"pwd1234"}' \
     http://localhost:8000/api/change-password
```

(#46)

diff --git a/tests/test b/tests/test
--- a/tests/test
+++ b/tests/test
@@ -29,6 +29,10 @@ INSTANCE="de305d54-75b4-431b-adb2-eb6b9e546014"
 
 NOTINSTANCE="deadbeef-75b4-431b-adb2-eb6b9e546014"
 
+testing () {
+    echo -e "\e[32m$1 \e[39m"
+}
+
 fail () {
     echo -e "\e[91mTest Failed: $1\e[39m"
     exit 1
@@ -56,7 +60,7 @@ run_db () {
 
 
 docker_setup () {
-    db > /dev/null <<EOF
+    db &> /dev/null <<EOF
 DROP SCHEMA public CASCADE;
 CREATE SCHEMA public
   AUTHORIZATION postgres;
@@ -69,7 +73,7 @@ EOF
     authservice adduser "$USER" "$PASSWORD" "$NAME"
     authservice adduser "$USER2" "$PASSWORD2" "$NAME" "12345"
 
-    db > /dev/null <<EOF
+    db &> /dev/null <<EOF
 INSERT INTO "instance" VALUES ('${INSTANCE}', 'instance1');
 INSERT INTO "user_instance" VALUES ( (SELECT "uuid" FROM "user" WHERE "email" = '${USER}')
                                    , (SELECT "uuid" FROM "instance" WHERE "name"='instance1'));
@@ -100,7 +104,6 @@ enter_nginx() {
 
 
 create_otp() {
-    echo "Creating OTP"
     if [[ -z $1 ]]; then
       LOGIN_USER=$USER
     else
@@ -114,14 +117,11 @@ create_otp() {
     RES=$($CURL -H "Content-Type: application/json" \
                 -d "{ \"user\": \"$LOGIN_USER\", \"password\": \"$LOGIN_PASSWORD\" }" \
                 http://$API/login)
-    if [[ ! $RES == '{"error":"One time password required"}' ]]; then
-      echo "Could not create OTP: $RES"
-      exit 1
-    fi
+    [[ $RES == '{"error":"One time password required"}' ]] || fail "Could not create OTP: $RES"
 }
 
 login() {
-    echo "logging in"
+    unset TOKEN
     if [[ -z $1 ]]; then
       LOGIN_USER=$USER
     else
@@ -143,23 +143,23 @@ login() {
                 http://$API/login)
 
     TOKEN=$(echo "$RES" | jq -r '.token.token')
-    echo "Got token: $TOKEN"
-    if [[ -z "$TOKEN" ]]; then
-       echo "Could not login: $RES"
-       exit 1
-    fi
+    [[ -n "$TOKEN" ]]
 }
 
 call() {
+    ENDPOINT=$1
+    shift
     RES=$($CURL -XPOST \
                 -o /dev/null \
                 -w %{http_code} \
                 -H "X-Instance: $INSTANCE" \
                 -H "X-Token: $TOKEN" \
-                "http://$API/$1"
+                "$@" \
+                "http://$API/$ENDPOINT"\
+
         )
     if [[ $RES -lt 200 || $RES -gt 300 ]]; then
-       fail "Calling http://$API/$1 failed with error code $RES"
+       fail "Calling http://$API/$ENDPOINT failed with error code $RES"
     fi
 }
 
@@ -192,90 +192,59 @@ runtest() {
 }
 
 docker_test() {
-    echo "Running setup"
-    docker_setup
-    echo "Trying to log in"
-    login
-    echo "Checking token"
+    docker_setup &> /dev/null
+    testing "Trying log in"
+    login || fail "could not log in"
+    testing "Checking token"
     RES=$($CURL -o /dev/null \
                 --write-out %{http_code}\
                 -H "X-Token: $TOKEN" \
                 http://$API/check-token)
-    if [[ $RES != "200" ]]; then
-      echo "Could not verify token got $RES"
-      exit 1
-    fi
-    echo "Trying to reach upstream resource"
+    [[ $RES == "200" ]] || fail "Could not verify token got $RES"
+
+    testing "Trying to reach upstream resource"
     RES=$($CURL -H "X-Instance: $INSTANCE" \
                 -H "X-Token: $TOKEN" \
                 http://$API/foo/index.html)
-    if [[ $RES != "foo!" ]]; then
-      echo "Could not retrieve foo.html, got $RES insted"
-      exit 1
-    fi
-    echo "Upstream says:" $RES
+    [[ $RES == "foo!" ]] || fail "Could not retrieve foo.html, got $RES insted"
 
-    echo "Trying to reach upstream resource without token"
+    testing "Trying to reach upstream resource without token"
     RES=$($CURL -o /dev/null \
                 -w %{http_code} \
                 -H "X-Instance: $INSTANCE" \
                 http://$API/index.htm)
-    if [[ $RES != "403" ]]; then
-      echo "Did not get authorization denied, instead got $RES"
-      exit 1
-    fi
+    [[ $RES == "403" ]] || fail "Did not get authorization denied, instead got $RES"
 
-    echo "Trying to reach upstream resource with bogus token"
+    testing "Trying to reach upstream resource with bogus token"
     RES=$($CURL -o /dev/null \
                 -w %{http_code} \
                 -H "X-Instance: $INSTANCE" \
                 -H "X-Token: bogus$TOKEN" \
                 http://$API/index.htm)
-    if [[ $RES != "403" ]]; then
-      echo "Did not get authorization denied, instead got $RES"
-      exit 1
-    fi
+    [[ $RES == "403" ]] || fail "Did not get authorization denied, instead got $RES"
 
-    echo "Trying / without a token"
-    RES=$($CURL http://$DOCKER_HOST/
-       )
-    if [[ $RES != "Authenticate!" ]]; then
-      echo "Did not get redirect , instead got $RES"
-      exit 1
-    fi
+    testing "Trying / without a token"
+    RES=$($CURL http://$DOCKER_HOST/ )
+    [[ $RES == "Authenticate!" ]]  || fail "Did not get redirect , instead got $RES"
 
-    echo "Trying /auth.html"
+    testing "Trying /auth.html"
     RES=$($CURL http://$DOCKER_HOST/auth.html)
-    if [[ $RES != "Authenticate!" ]]; then
-      echo "Did not get auth.html, instead got $RES"
-      exit 1
-    else
-      echo "Got /auth.html"
-    fi
+    [[ $RES == "Authenticate!" ]] || fail "Did not get auth.html, instead got $RES"
 
-    echo "Trying /auth.html with token"
+    testing "Trying /auth.html with token"
     RES=$($CURL -o /dev/null \
                 -w %{http_code} \
                 -H "X-Instance: $INSTANCE" \
                 --cookie "token=$TOKEN" \
                 http://$DOCKER_HOST/auth.html)
-    if [[ $RES != "303" ]]; then
-      echo "Did not get redirect, instead got $RES"
-      exit 1
-    else
-      echo "Got redirect"
-    fi
+    [[ $RES == "303" ]] || fail "Did not get redirect, instead got $RES"
 
-    echo "Trying to get user info"
+    testing "Trying to get user info"
     RES=$($CURL --cookie "token=$TOKEN" \
                 http://$API/user-info)
-    if [[ $(echo "$RES" | jq -r '.email') != "no@spam.please" ]]; then
-      echo "Could not get user info"
-      exit 1
-    fi
-    echo "Got user info"
+    [[ $(echo "$RES" | jq -r '.email') == "no@spam.please" ]] || fail "Could not get user info"
 
-    echo "Getting header info"
+    testing "Getting header info"
     RES=$($CURL -I \
                 --cookie "token=$TOKEN" \
                 -H "X-Instance: $INSTANCE" \
@@ -286,16 +255,10 @@ docker_test() {
                    | tr -d '\r' \
                    | awk 'BEGIN {FS=": "}/^Last-Modified/{print $2}'
            )
-    if [[ -z $ETAG ]]; then
-      echo "No ETag received"
-      exit 1
-    fi
-    if [[ -z $LASTMOD ]]; then
-      echo "No Last-Modified received"
-      exit 1
-    fi
+    [[ -n $ETAG ]] || fail "No ETag received"
+    [[ -n $LASTMOD ]] || fail "No Last-Modified received"
 
-    echo "Trying If-Modified-Since"
+    testing "Trying If-Modified-Since"
     RES=$($CURL --cookie "token=$TOKEN" \
                 -H "X-Instance: $INSTANCE" \
                 -H "If-Modified-Since: $LASTMOD" \
@@ -303,12 +266,9 @@ docker_test() {
                 -w %{http_code} \
                 http://$DOCKER_HOST/index.html
        )
-    if [[ $RES != "304" ]]; then
-      echo "If-Modified-Since did not result in 304, got $RES instead"
-      exit 1
-    fi
+    [[ $RES == "304" ]] || fail "If-Modified-Since did not result in 304, got $RES instead"
 
-    echo "Trying If-None-Match"
+    testing "Trying If-None-Match"
     RES=$($CURL --cookie "token=$TOKEN" \
                 -H "X-Instance: $INSTANCE" \
                 -H "If-None-Match: $ETAG" \
@@ -316,12 +276,9 @@ docker_test() {
                 -w %{http_code} \
                 http://$DOCKER_HOST/index.html
        )
-    if [[ $RES != "304" ]]; then
-      echo "If-None-Match did not result in 304, got $RES instead"
-      exit 1
-    fi
+    [[ $RES == "304" ]] || fail "If-None-Match did not result in 304, got $RES instead"
 
-    echo "Trying If-None-Match with non-matching ETag"
+    testing "Trying If-None-Match with non-matching ETag"
     RES=$($CURL --cookie "token=$TOKEN" \
                 -H "X-Instance: $INSTANCE" \
                 -H "If-None-Match: \"bogus\"" \
@@ -329,12 +286,9 @@ docker_test() {
                 -w %{http_code} \
                 http://$DOCKER_HOST/index.html
        )
-    if [[ $RES != "200" ]]; then
-      echo "If-None-Match did not result in 304, got $RES instead"
-      exit 1
-    fi
+    [[ $RES == "200" ]] || fail "If-None-Match did not result in 304, got $RES instead"
 
-    echo "Trying If-Modified-Since + If-None-Match"
+    testing "Trying If-Modified-Since + If-None-Match"
     RES=$($CURL -H "X-Instance: $INSTANCE" \
                 --cookie "token=$TOKEN" \
                 -H "If-Modified-Since: $LASTMOD" \
@@ -343,12 +297,9 @@ docker_test() {
                 -w %{http_code} \
                 http://$DOCKER_HOST/index.html
        )
-    if [[ $RES != "304" ]]; then
-      echo "If-Modified-Since + If-None-Match did not result in 304, got $RES instead"
-      exit 1
-    fi
+    [[ $RES == "304" ]] || fail "If-Modified-Since + If-None-Match did not result in 304, got $RES instead"
 
-    echo "Trying If-Modified-Since + If-None-Match without token"
+    testing "Trying If-Modified-Since + If-None-Match without token"
     RES=$($CURL -I "X-Instance: $INSTANCE" \
                 http://$DOCKER_HOST/index.html)
 
@@ -357,15 +308,8 @@ docker_test() {
                    | tr -d '\r' \
                    | awk 'BEGIN {FS=": "}/^Last-Modified/{print $2}'
            )
-    if [[ -z $ETAG ]]; then
-      echo "No ETag received: \n$RES"
-      exit 1
-    fi
-    if [[ -z $LASTMOD ]]; then
-      echo "No Last-Modified received: \n$RES"
-      exit 1
-    fi
-
+    [[ -n $ETAG ]] || fail "No ETag received: \n$RES"
+    [[ -n $LASTMOD ]] || fail "No Last-Modified received: \n$RES"
     RES=$($CURL -H "X-Instance: $INSTANCE" \
                 -H "If-Modified-Since: $LASTMOD" \
                 -H "If-None-Match: $ETAG" \
@@ -373,90 +317,72 @@ docker_test() {
                 -w %{http_code} \
                 http://$DOCKER_HOST/index.html
        )
-    if [[ $RES != "304" ]]; then
-      echo "If-Modified-Since + If-None-Match did not result in 304, got $RES instead"
-      exit 1
-    fi
+    [[ $RES == "304" ]] || fail "If-Modified-Since + If-None-Match did not result in 304, got $RES instead"
 
-    echo "Trying index.html without instance"
+    testing "Trying index.html without instance"
     RES=$($CURL --cookie "token=$TOKEN" \
                 -o /dev/null \
                 -w %{http_code} \
                 http://$DOCKER_HOST/index.html
        )
-    if [[ $RES != "200" ]]; then
-      echo "Could not get index.html without instance"
-      exit 1
-    fi
+    [[ $RES == "200" ]] || fail "Could not get index.html without instance"
 
-    echo "Trying index.html with wrong instance"
+    testing "Trying index.html with wrong instance"
     RES=$($CURL -H "X-Instance: $NOTINSTANCE" \
                 --cookie "token=$TOKEN" \
                 -o /dev/null \
                 -w %{http_code} \
                 http://$API/index.html
        )
-    if [[ $RES != "403" ]]; then
-      echo "Did not get 403, got $RES instead"
-      exit 1
-    fi
+    [[ $RES == "403" ]] || fail "Did not get 403, got $RES instead"
 
-
-    echo "Trying / without token (should fail)"
+    testing "Trying / without token (should fail)"
     RES=$($CURL http://$DOCKER_HOST/ )
-    if [[ $RES != "Authenticate!" ]]; then
-      echo "Did not receive Authenticate!, got $RES instead"
-      exit 1
-    fi
+    [[ $RES == "Authenticate!" ]] || fail "Did not receive Authenticate!, got $RES instead"
 
-    echo "Trying /index.html without token (should fail)"
+    testing "Trying /index.html without token (should fail)"
     RES=$($CURL http://$DOCKER_HOST/index.html )
-    if [[ $RES != "Authenticate!" ]]; then
-      echo "Did not receive Authenticate!, got $RES instead"
-      exit 1
-    fi
+    [[ $RES == "Authenticate!" ]] || fail "Did not receive Authenticate!, got $RES instead"
 
-    echo "Trying /foo.html without token"
+    testing "Trying /foo.html without token"
     RES=$($CURL http://$DOCKER_HOST/foo.html )
-    if [[ $RES != "foo!" ]]; then
-      echo "Did not receive foo!, got $RES instead"
-      exit 1
-    fi
+    [[ $RES == "foo!" ]] || fail "Did not receive foo!, got $RES instead"
 
-    echo "Testing otp"
+    testing "Testing otp"
     create_otp $USER2 $PASSWORD2
     get_otp
-    if [[ -z $OTP ]]; then
-      echo "Could not get OTP"
-    else
-        echo "Got OTP: $OTP"
-    fi
+    [[ -n $OTP ]] || fail "Could not get OTP"
     OTP=$(echo $OTP | tr '[:upper:]' '[:lower:]')
-    echo "trying OTP $OTP"
-    login $USER2 $PASSWORD2 $OTP
+    login $USER2 $PASSWORD2 $OTP || fail "could not log in"
 
-    echo "Testing logout"
+    testing "Testing logout"
     logout
     RES=$($CURL -H "X-Instance: $INSTANCE" \
                 -H "X-Token: $TOKEN" \
                 -o /dev/null \
                 -w %{http_code} \
                 http://$API/foo/index.html)
-    if [[ $RES != "403" ]]; then
-      echo "Accessing resource after logout didn't lead to 403, returned $RES instead"
-      exit 1
-    fi
+    [[ $RES == "403" ]] || fail "Accessing resource after logout didn't lead to 403, returned $RES instead"
 
-    echo "Testing disable-sessions"
-    login
+    testing "Testing disable-sessions"
+    login || fail "could not log in"
     OLDTOKEN=$TOKEN
-    login
+    login || fail "could not log in"
     check_upstream || fail "Could not reach upstream"
     call "disable-sessions"
     check_upstream || fail "Disable-sessions disabled current session"
     TOKEN=$OLDTOKEN
     check_upstream && fail "Sessions where not disabled"
 
+    testing "Testing password change"
+    docker_setup &> /dev/null
+    login || fail "could not log in"
+    call "change-password" \
+         -H "Content-Type: application/json" \
+         -d "{\"oldPasword\":\"$PASSWORD\",\"newPassword\":\"$PASSWORD2\"}"
+    logout
+    login $USER $PASSWORD2 || fail "Could not login with new password"
+    login && fail "could still log on with old credentials"
 }
 
 docker_rebuild() {
