Add password reset info endpoint

diff --git a/tests/test b/tests/test
--- a/tests/test
+++ b/tests/test
@@ -37,8 +37,13 @@ testing () {
     echo -e "\e[32m$1 \e[39m"
 }
 
+
+errmsg() {
+    echo -e "\e[91mTest Failed: $*\e[39m"
+}
+
 fail () {
-    echo -e "\e[91mTest Failed: $1\e[39m"
+    errmsg "$@"
     exit 1
 }
 
@@ -56,7 +61,7 @@ db () {
 
 run_db () {
     docker exec \
-           -it $AUTHSERVICE_CONTAINER psql \
+           -it $DB_CONTAINER psql \
            -h $DB_HOST \
            -U $DB_USER \
            $DB_DATABASE "$@"
@@ -150,20 +155,36 @@ login() {
     [[ -n "$TOKEN" ]]
 }
 
+http() {
+    tmpfile=$(mktemp --tmpdir auth-service.tmp.XXXXX) || fail "Could not make temporary file"
+    trap "rm -f $tmpfile" EXIT
+    res=$($CURL -o "$tmpfile" -w "%{http_code}" "$@")
+    if [[ "$res" -lt 200 || "$res" -gt 300 ]]; then
+      echo "http error (response code $res)"
+      echo "To reproduce : $CURL $*"
+    else
+        cat "$tmpfile"
+    fi
+}
+
 call() {
+    tmpfile=$(mktemp --tmpdir auth-service.tmp.XXXXX) || fail "Could not make temporary file"
+    trap "rm -f $tmpfile" EXIT
     ENDPOINT=$1
     shift
     RES=$($CURL -XPOST \
-                -o /dev/null \
+                -o "$tmpfile" \
                 -w "%{http_code}" \
                 -H "X-Instance: $INSTANCE" \
                 -H "X-Token: $TOKEN" \
                 "$@" \
                 "http://$API/$ENDPOINT"\
-
-        )
-    if [[ $RES -lt 200 || $RES -gt 300 ]]; then
-       fail "Calling http://$API/$ENDPOINT failed with error code $RES"
+       )
+    if [[ "$RES" -lt 200 || "$RES" -gt 300 ]]; then
+      echo "$RES when calling POST http://$API/$ENDPOINT"
+      cat "$tmpfile"
+      echo "Command was: $CURL -XPOST -H \"X-Instance: $INSTANCE\" -H \"X-Token: $TOKEN\" \"$*\" \"http://$API/$ENDPOINT"\"
+      fail "call threw error"
     fi
 }
 
@@ -191,21 +212,23 @@ clearEmail() {
     email messages -XDELETE -o /dev/null
 }
 
+
+# Reads the latest email and tries to extract the token; stores it in $token
 emailGetToken() {
     tmpfile=$(mktemp --tmpdir auth-service.tmp.XXXXX) || fail "Could not make temporary file"
-    trap "rm -r $tmpfile" EXIT
+    trap "rm -f $tmpfile" EXIT
     res=$($CURL --silent -w "%{http_code}" "http://$EMAIL_API/messages" -o "$tmpfile")
     if [[ $res -lt 200 || $res -gt 300 ]]; then
        fail "Failed with error code $res"
     fi
-    token=$(< "$tmpfile" \
-      jq -r '.[0] | .MIME.Parts | .[1] | .Body' \
-      | perl -n -e '/\?token=3D([[:alnum:]]+)/ && print $1')
-
-    [[ -n "$token" ]] || fail "could not get token"
-
     # This is a bit hacky, we rely on the email to contain a link of the form
     # "?token=<token>" the "3D" is there fore MIME reasons
+
+    token=$(< "$tmpfile" \
+      jq -r '.[0] | .MIME.Parts | .[1] | .Body' \
+              | perl -n -e '/\?token=3D([[:alnum:]]+)<\/a>/ && print $1')
+    [[ -n "$token" ]] || fail "could not get token"
+
 }
 
 # run _local_ test
@@ -430,13 +453,31 @@ docker_test() {
          -H "Content-Type: application/json" \
          -d "{\"email\": \"$USER\"}"
     emailGetToken
+    call "reset-password" -H "Content-Type: application/json" \
+         -d "{\"token\":\"$token\", \"newPassword\":\"newpwd\"}"
+    login "$USER" "newpwd"
+    # Check that we can't login with the old credentials
+    login && fail "password wasn't changed"
+
+    testing "Password reset info"
+    call "request-password-reset" \
+         -H "Content-Type: application/json" \
+         -d "{\"email\": \"$USER\"}"
+    emailGetToken
+    $CURL "http://$API/reset-password-info/$token"
 
     testing "Password reset with unknown email"
     call "request-password-reset" \
          -H "Content-Type: application/json" \
          -d "{\"email\": \"unknown_user@no-address.abc\"}"
+    call "request-password-reset" \
+         -H "Content-Type: application/json" \
+         -d "{\"email\": \"$USER\"}"
+    emailGetToken
+    http "http://$API/reset-password-info?token=$token"
 
 }
+
 
 docker_rebuild() {
     set -e
